# A profile specifically for Anbernic RG devices

ifeq (,$(wildcard ../profile/Makefile.arm))
$(error Something went wrong)
endif

# TODO: probably consider better pathing, perhaps use an absolute dir $VAR
include ../profile/Makefile.arm

NO_GLEW = 1
NO_X11 = 1
NO_PULSE = 1
USE_OPENGLES = 1

ARCH_CFLAGS = -fPIE -march=armv8-a+crc+crypto -mtune=cortex-a72
ARCH_CXXFLAGS := $(ARCH_CFLAGS)
